### ISSUE TITLE
Custom area bug: teleport to the Sahara

### ISSUE THREAD

**Issue by lhilarides** [Vizzuality/mangrove-atlas#702]
As soon as you click on the "Delete custom area" button, you are teleported to the middle of the Sahara. I tested on Windows 11 with the latest Firefox and Chrome versions. Expected behavior is that you stay where you are on the map

![image](https://user-images.githubusercontent.com/3919721/230647408-f9bbb6f1-14fa-4a2c-b8db-54e59c3fb8a5.png)

**Comment by dhakelila** [comment]
This is now fixed.

**Comment by lhilarides** [comment]
It's fixed when you click "Remove Custom Area", but it still occurs when you click the "Reset page" button

![image](https://github.com/Vizzuality/mangrove-atlas/assets/3919721/ba59f999-9dbf-498a-89bb-4fca00ecce3a)
